import jsPDF from "jspdf";

export default function PDFGenerator({ data }) {
  const downloadPDF = async () => {
    const pdf = new jsPDF("p", "mm", "a4");

    // 🔹 Load Logo as base64
    const loadLogo = async () => {
      return new Promise((resolve, reject) => {
        const img = new Image();
        img.crossOrigin = "anonymous";
        img.src = "/logo.png";
        img.onload = () => {
          const canvas = document.createElement("canvas");
          const ctx = canvas.getContext("2d");
          canvas.width = img.width;
          canvas.height = img.height;
          ctx.drawImage(img, 0, 0);
          const dataURL = canvas.toDataURL("image/png");
          resolve(dataURL);
        };
        img.onerror = reject;
      });
    };

    const logo = await loadLogo();

    // 🔹 Header
    const addHeader = (logoData) => {
      pdf.addImage(logoData, "PNG", 15, 8, 20, 20);

      pdf.setFontSize(12);
      pdf.setFont(undefined, "bold");
      pdf.text("Work Report", 40, 18);

      pdf.setDrawColor(220);
      pdf.line(10, 30, 200, 30);
    };

    // 🔹 Footer
    const addFooter = (pageNo) => {
      pdf.setFontSize(9);
      pdf.setTextColor(150);
      pdf.text(`Page ${pageNo}`, 105, 290, { align: "center" });
      pdf.text("Generated by Smart Genie (SG)", 200, 290, { align: "right" });
      pdf.setTextColor(0);
    };

    // 🔹 COVER PAGE
    pdf.setFontSize(22);
    pdf.setFont(undefined, "bold");
    pdf.text(data.title, 105, 110, { align: "center" });

    pdf.setFontSize(14);
    pdf.setFont(undefined, "normal");
    pdf.text("Work Report", 105, 125, { align: "center" });

    pdf.setFontSize(12);
    pdf.text(`Client: ${data.clientName || "-"}`, 105, 145, { align: "center" });
    pdf.text(`Location: ${data.location || "-"}`, 105, 155, { align: "center" });
    pdf.text(`Date: ${data.date}`, 105, 170, { align: "center" });

    addFooter(1);

    let pageNo = 2;

    // 🔹 CONTENT PAGES
    for (let i = 0; i < data.images.length; i++) {
      pdf.addPage();

      addHeader(logo);

      pdf.setFontSize(10);
      pdf.setTextColor(120);
      pdf.text(`Client: ${data.clientName || "-"}`, 15, 35);
      pdf.text(`Location: ${data.location || "-"}`, 15, 40);
      pdf.setTextColor(0);

      const img = data.images[i];
      const note = data.notes[i];

      // Convert image to base64
      const imgData = await new Promise((resolve) => {
        const reader = new FileReader();
        reader.onload = () => resolve(reader.result);
        reader.readAsDataURL(img);
      });

      const image = await new Promise((resolve) => {
        const imgObj = new Image();
        imgObj.src = imgData;
        imgObj.onload = () => resolve(imgObj);
      });

      const imgWidth = 180;
      const imgHeight = (image.height * imgWidth) / image.width;

      let yStart = 45;

      pdf.addImage(imgData, "JPEG", 15, yStart, imgWidth, imgHeight);

      pdf.setFontSize(12);
      pdf.setFont("helvetica", "normal"); // Arial-like font
      pdf.setFontSize(11);

    // Wrap text properly
      const splitText = pdf.splitTextToSize(note || "", 180);

    // Calculate safe Y position
      let textY = yStart + imgHeight + 15;

    // Prevent overflow (if near page bottom)
      if (textY > 260) {
      pdf.addPage();
      addHeader();
      textY = 40;
    }

    // Add text
      pdf.text(splitText, 15, textY);

      pdf.setDrawColor(230);
      pdf.line(15, yStart + imgHeight + 30, 195, yStart + imgHeight + 30);

      addFooter(pageNo);
      pageNo++;
    }

    // 🔹 SIGNATURE PAGE
    pdf.addPage();

    addHeader(logo);

    pdf.setFontSize(14);
    pdf.setFont(undefined, "bold");
    pdf.text("Approval", 15, 50);

    pdf.setFont(undefined, "normal");
    pdf.setFontSize(12);

    pdf.text("Client Signature:", 15, 80);
    pdf.line(15, 90, 80, 90);

    pdf.text("Authorized Signature:", 120, 80);
    pdf.line(120, 90, 185, 90);

    addFooter(pageNo);

    pdf.save("Work_Report.pdf");
  };

  return (
    <button
      onClick={downloadPDF}
      style={{
        padding: "12px 24px",
        background: "#111",
        color: "#fff",
        border: "none",
        borderRadius: "6px",
        cursor: "pointer",
      }}
    >
      Download Report
    </button>
  );
}